// <auto-generated />
namespace haunt_map_users.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateHauntWithGuid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateHauntWithGuid));
        
        string IMigrationMetadata.Id
        {
            get { return "201706130406139_updateHauntWithGuid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
